// flow-typed signature: b5cc0c0c03121a904eb5acbe1d6c2433
// flow-typed version: <<STUB>>/redux-persist_v4.10.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist/dist/redux-persist' {
  declare module.exports: any;
}

declare module 'redux-persist/dist/redux-persist.min' {
  declare module.exports: any;
}

declare module 'redux-persist/es/autoRehydrate' {
  declare module.exports: any;
}

declare module 'redux-persist/es/constants' {
  declare module.exports: any;
}

declare module 'redux-persist/es/createPersistor' {
  declare module.exports: any;
}

declare module 'redux-persist/es/createTransform' {
  declare module.exports: any;
}

declare module 'redux-persist/es/defaults/asyncLocalStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/es/defaultStorages' {
  declare module.exports: any;
}

declare module 'redux-persist/es/getStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/es/index' {
  declare module.exports: any;
}

declare module 'redux-persist/es/persistStore' {
  declare module.exports: any;
}

declare module 'redux-persist/es/purgeStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/es/utils/isStatePlainEnough' {
  declare module.exports: any;
}

declare module 'redux-persist/es/utils/setImmediate' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/autoRehydrate' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/createPersistor' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/createTransform' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/defaults/asyncLocalStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/defaultStorages' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/getStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/index' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/persistStore' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/purgeStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/utils/isStatePlainEnough' {
  declare module.exports: any;
}

declare module 'redux-persist/lib/utils/setImmediate' {
  declare module.exports: any;
}

declare module 'redux-persist/src/autoRehydrate' {
  declare module.exports: any;
}

declare module 'redux-persist/src/constants' {
  declare module.exports: any;
}

declare module 'redux-persist/src/createPersistor' {
  declare module.exports: any;
}

declare module 'redux-persist/src/createTransform' {
  declare module.exports: any;
}

declare module 'redux-persist/src/defaults/asyncLocalStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/src/defaultStorages' {
  declare module.exports: any;
}

declare module 'redux-persist/src/getStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/src/index' {
  declare module.exports: any;
}

declare module 'redux-persist/src/persistStore' {
  declare module.exports: any;
}

declare module 'redux-persist/src/purgeStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/src/utils/isStatePlainEnough' {
  declare module.exports: any;
}

declare module 'redux-persist/src/utils/setImmediate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist/dist/redux-persist.js' {
  declare module.exports: $Exports<'redux-persist/dist/redux-persist'>;
}
declare module 'redux-persist/dist/redux-persist.min.js' {
  declare module.exports: $Exports<'redux-persist/dist/redux-persist.min'>;
}
declare module 'redux-persist/es/autoRehydrate.js' {
  declare module.exports: $Exports<'redux-persist/es/autoRehydrate'>;
}
declare module 'redux-persist/es/constants.js' {
  declare module.exports: $Exports<'redux-persist/es/constants'>;
}
declare module 'redux-persist/es/createPersistor.js' {
  declare module.exports: $Exports<'redux-persist/es/createPersistor'>;
}
declare module 'redux-persist/es/createTransform.js' {
  declare module.exports: $Exports<'redux-persist/es/createTransform'>;
}
declare module 'redux-persist/es/defaults/asyncLocalStorage.js' {
  declare module.exports: $Exports<'redux-persist/es/defaults/asyncLocalStorage'>;
}
declare module 'redux-persist/es/defaultStorages.js' {
  declare module.exports: $Exports<'redux-persist/es/defaultStorages'>;
}
declare module 'redux-persist/es/getStoredState.js' {
  declare module.exports: $Exports<'redux-persist/es/getStoredState'>;
}
declare module 'redux-persist/es/index.js' {
  declare module.exports: $Exports<'redux-persist/es/index'>;
}
declare module 'redux-persist/es/persistStore.js' {
  declare module.exports: $Exports<'redux-persist/es/persistStore'>;
}
declare module 'redux-persist/es/purgeStoredState.js' {
  declare module.exports: $Exports<'redux-persist/es/purgeStoredState'>;
}
declare module 'redux-persist/es/utils/isStatePlainEnough.js' {
  declare module.exports: $Exports<'redux-persist/es/utils/isStatePlainEnough'>;
}
declare module 'redux-persist/es/utils/setImmediate.js' {
  declare module.exports: $Exports<'redux-persist/es/utils/setImmediate'>;
}
declare module 'redux-persist/lib/autoRehydrate.js' {
  declare module.exports: $Exports<'redux-persist/lib/autoRehydrate'>;
}
declare module 'redux-persist/lib/constants.js' {
  declare module.exports: $Exports<'redux-persist/lib/constants'>;
}
declare module 'redux-persist/lib/createPersistor.js' {
  declare module.exports: $Exports<'redux-persist/lib/createPersistor'>;
}
declare module 'redux-persist/lib/createTransform.js' {
  declare module.exports: $Exports<'redux-persist/lib/createTransform'>;
}
declare module 'redux-persist/lib/defaults/asyncLocalStorage.js' {
  declare module.exports: $Exports<'redux-persist/lib/defaults/asyncLocalStorage'>;
}
declare module 'redux-persist/lib/defaultStorages.js' {
  declare module.exports: $Exports<'redux-persist/lib/defaultStorages'>;
}
declare module 'redux-persist/lib/getStoredState.js' {
  declare module.exports: $Exports<'redux-persist/lib/getStoredState'>;
}
declare module 'redux-persist/lib/index.js' {
  declare module.exports: $Exports<'redux-persist/lib/index'>;
}
declare module 'redux-persist/lib/persistStore.js' {
  declare module.exports: $Exports<'redux-persist/lib/persistStore'>;
}
declare module 'redux-persist/lib/purgeStoredState.js' {
  declare module.exports: $Exports<'redux-persist/lib/purgeStoredState'>;
}
declare module 'redux-persist/lib/utils/isStatePlainEnough.js' {
  declare module.exports: $Exports<'redux-persist/lib/utils/isStatePlainEnough'>;
}
declare module 'redux-persist/lib/utils/setImmediate.js' {
  declare module.exports: $Exports<'redux-persist/lib/utils/setImmediate'>;
}
declare module 'redux-persist/src/autoRehydrate.js' {
  declare module.exports: $Exports<'redux-persist/src/autoRehydrate'>;
}
declare module 'redux-persist/src/constants.js' {
  declare module.exports: $Exports<'redux-persist/src/constants'>;
}
declare module 'redux-persist/src/createPersistor.js' {
  declare module.exports: $Exports<'redux-persist/src/createPersistor'>;
}
declare module 'redux-persist/src/createTransform.js' {
  declare module.exports: $Exports<'redux-persist/src/createTransform'>;
}
declare module 'redux-persist/src/defaults/asyncLocalStorage.js' {
  declare module.exports: $Exports<'redux-persist/src/defaults/asyncLocalStorage'>;
}
declare module 'redux-persist/src/defaultStorages.js' {
  declare module.exports: $Exports<'redux-persist/src/defaultStorages'>;
}
declare module 'redux-persist/src/getStoredState.js' {
  declare module.exports: $Exports<'redux-persist/src/getStoredState'>;
}
declare module 'redux-persist/src/index.js' {
  declare module.exports: $Exports<'redux-persist/src/index'>;
}
declare module 'redux-persist/src/persistStore.js' {
  declare module.exports: $Exports<'redux-persist/src/persistStore'>;
}
declare module 'redux-persist/src/purgeStoredState.js' {
  declare module.exports: $Exports<'redux-persist/src/purgeStoredState'>;
}
declare module 'redux-persist/src/utils/isStatePlainEnough.js' {
  declare module.exports: $Exports<'redux-persist/src/utils/isStatePlainEnough'>;
}
declare module 'redux-persist/src/utils/setImmediate.js' {
  declare module.exports: $Exports<'redux-persist/src/utils/setImmediate'>;
}
